name: fluttertest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  cached_network_image:
  flutter_cache_manager: ^3.4.1
  video_player: ^2.10.1
  image: ^4.5.4
  chewie:
  app_links:
  file_picker:
  url_launcher:
  firebase_core: ^4.2.1
  firebase_database:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  firebase_messaging:
  firebase_crashlytics:
  logger: ^2.6.2
  shared_preferences: ^2.5.4
  google_fonts: ^6.3.3
  dio: ^5.9.0
  flutter_webrtc: ^1.2.1
  uuid: ^4.5.2
  web_socket_channel: ^3.0.3
  record: ^6.1.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
